import { Message, GuildMember } from 'discord.js';
import { Op } from 'sequelize';
import { Context } from '../types';
import { getLogChannel } from '../utils/discordHelpers';

const CODE_PATTERN = /V-[A-HJ-NP-Z2-9]{6}/i;
const DEFAULT_EXPIRATION_SECONDS = 86400; // 24 hours

async function getWelcomeChannelId(tables: any, guildId: string): Promise<string | null> {
    const config = await tables.Config.findOne({
        where: { key: `welcome_channel_${guildId}` },
    });
    return config?.value || null;
}

async function getVerifyExpiration(tables: any, guildId: string): Promise<number> {
    const config = await tables.Config.findOne({
        where: { key: `verify_expiration_${guildId}` },
    });
    return config ? parseInt(config.value, 10) : DEFAULT_EXPIRATION_SECONDS;
}

export default async (message: Message, context: Context): Promise<boolean> => {
    const { tables, log } = context;

    // Must be in a guild
    if (!message.guild || !message.guildId) {
        return false;
    }

    // Check if this is the welcome channel
    const welcomeChannelId = await getWelcomeChannelId(tables, message.guildId);
    if (!welcomeChannelId || message.channelId !== welcomeChannelId) {
        return false;
    }

    // Look for verification code pattern
    const match = message.content.match(CODE_PATTERN);
    if (!match) {
        return false;
    }

    const code = match[0].toUpperCase();

    try {
        // Get expiration time
        const expirationSeconds = await getVerifyExpiration(tables, message.guildId);
        const expirationDate = new Date(Date.now() - expirationSeconds * 1000);

        // Look up the code
        const verificationCode = await tables.VerificationCode.findOne({
            where: {
                code,
                guildId: message.guildId,
                used: false,
                createdAt: { [Op.gte]: expirationDate },
            },
        });

        // If code is invalid, expired, or used - stay silent
        if (!verificationCode) {
            return false;
        }

        // Get the member
        const member = message.member as GuildMember;
        if (!member) {
            return false;
        }

        // Check if user already has the role - stay silent
        if (member.roles.cache.has(verificationCode.roleId)) {
            return false;
        }

        // Grant the role
        const role = message.guild.roles.cache.get(verificationCode.roleId);
        if (!role) {
            log.error(
                { roleId: verificationCode.roleId, guildId: message.guildId },
                'Role not found for verification code',
            );
            return false;
        }

        await member.roles.add(role);

        // Mark code as used
        await tables.VerificationCode.update(
            {
                used: true,
                usedBy: message.author.id,
                usedAt: new Date(),
            },
            {
                where: { code },
            },
        );

        // Delete the user's message
        try {
            await message.delete();
        } catch (deleteError) {
            log.warn({ error: deleteError, messageId: message.id }, 'Failed to delete verification message');
        }

        // Log to log channel if configured
        const logChannel = await getLogChannel(message.guild, tables, log);
        if (logChannel) {
            const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
            const logMessage = `[${timestamp}] <@${message.author.id}> used code ${code} `
                + `(generated by <@${verificationCode.generatorId}>) → granted @${role.name}`;
            try {
                await logChannel.send(logMessage);
            } catch (logError) {
                log.warn({ error: logError }, 'Failed to send verification log message');
            }
        }

        log.info({
            code,
            guildId: message.guildId,
            userId: message.author.id,
            generatorId: verificationCode.generatorId,
            roleId: verificationCode.roleId,
            roleName: role.name,
        }, 'Verification code used successfully');

        return true;
    } catch (error) {
        log.error({ error, code, guildId: message.guildId }, 'Error processing verification code');
        return false;
    }
};
