# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0
    working_directory: ~/alia
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test -- --ci --testResultsProcessor="jest-junit" --collectCoverage=true
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run:
          name: Linter
          command: npm run lint -- --format junit -o reports/junit/js-lint-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage
  deploy:
    docker:
      - image: circleci/node:11.9.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:1d:75:08:5a:42:1e:cb:cd:61:02:47:54:5e:08:be"
      - run:
          name: Fix host authenticity
          command: |
            ssh-keyscan ${HOST_IP} >> ~/.ssh/known_hosts
      - run:
          name: Deploy master
          command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh root@${HOST_IP} 'cd /var/www/alia-bot/scripts && . deploy.sh'; else echo "Skipped"; fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
