name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-ci-status:
    runs-on: ubuntu-latest
    outputs:
      ci-passed: ${{ steps.check-ci.outputs.result }}
    steps:
      - name: Check CI Status
        id: check-ci
        uses: actions/github-script@v7
        with:
          script: |
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha
            });
            
            const requiredChecks = ['Lint', 'Test (20)', 'Test (21)', 'Coverage'];
            const completedChecks = checkRuns.check_runs.filter(check => 
              requiredChecks.includes(check.name) && 
              check.status === 'completed' && 
              check.conclusion === 'success'
            );
            
            console.log(`Found ${completedChecks.length}/${requiredChecks.length} completed checks`);
            return completedChecks.length === requiredChecks.length;

  claude-review:
    needs: check-ci-status
    runs-on: ubuntu-latest
    if: needs.check-ci-status.outputs.ci-passed == 'true'
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage
            
            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
          
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

